# todo 之后会有dev和prod的两套配置。先凑合都放在application里面
server:
  port: 8080

# 数据库的相关配置
spring:
  datasource:
    url: jdbc:mysql://47.99.148.160:3306/qmoj_dev?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMutiQueries=true
    username: test
    password: test123.
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis的配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/*.xml

# 日志的配置,先简单配置一下。之后再配置根据时间分割
logging:
  level:
    root : info
  file:
    path: ./logs
# HttpClient相关配置
http:
  # 最大连接数
  maxTotal: 100
  # 并发数
  defaultMaxPerRoute: 20
  # 创建连接的最长时间
  connectTimeout: 1000
  # 从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  # 数据传输的最长时间
  socketTimeout: 10000
  # 提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

# LeetCode平台相关配置
leetCode:
  loginName: 524472212@qq.com
  passWord: 199654088

